my_ootd/app/urls.py
from django.urls import path, reverse_lazy, reverse
from django.contrib.auth import views as auth_views
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.root, name='root'),
    path('my', views.my, name='my'),
    path('sign-up', views.sign_up, name='sign_up'),
    path('login', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    # path('logout', auth_views.LogoutView.as_view(template_name='app/main.html'), name='logout'),
    path('logout', views._logout, name='logout'),
    path('color', views.personal_color, name='personal_color'),
    path('mycloset', views.post_cloth, name='mycloset'),
    path('update_cloth', views.update_cloth, name='update_cloth'),
    path('create_user', views.create_user, name='create_user'),
    path('color_match_test', views.get_close_color, name='color_match_test'),
    path('select_color_test', views.select_color_test, name='select_color_test'),

    # ajax
    path('retry_recommend_cody', views.retry_recommend_cody, name='retry_recommend_cody'),
    path('save_my_style', views.save_my_style, name='save_my_style'),
    path('clothes_category', views.clothes_category, name='clothes_category'),
]

my_ootd/my_ootd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_ootd/app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />
    <title>Mobile Coding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0" />
    <meta name="format-detection" content="telephone=no" />
    <!-- 부트스트랩 css 사용 -->
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'custom.css' %}">
    <link rel="stylesheet" href="{% static 'modal.css' %}">
    <link rel="apple-touch-icon" href="경로/이미지파일명.png" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>

    <style>
    </style>

</head>

<body>
    <div id="app">
        <header id="header">
            <nav class="navbar bg-white border-bottom">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">
                        <img src="{% static 'icons/logo_icon.png' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
                        <h3 style="display:inline; font-family:SEBANG_Gothic_Bold">#My_OOTD</h3>
                    </a>
                    <div class="top_icons">
                        <div class="search_button px-1 ">
                            <a href="#">
                            <img src="{% static 'icons/search_icon.svg' %}" alt="Search" width="30" height="24" class="d-inline-block align-text-top" >   
                            </a>
                        </div>
                        <div class="notification_button px-1 position-relative">
                            <a href="#">
                            <img src="{% static 'icons/bell_icon.svg' %}" alt="Notification" width="30" height="24" class="d-inline-block align-text-top">
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>

        {% block content %}
            {% comment %} base.html을 상속한 템플릿에서 구현해야 하는 영역 {% endcomment %}
        {% endblock %}

        <footer id="footer">
            <div class="py-5 bg-dark container-fluid px-4"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
            <div class="py-4 bg-dark container-fluid"></div>
        </footer>

        <nav id="fixed_bar">
            <div class="bottom_nav_bar btn-group" style="width:100%">
                <a href="{% url 'app:root' %}" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/home_icon.svg' %}" alt="add_icon">
                    <div style="font-family:Noto Sans KR">홈</div>
                </a>
<!--                <a href="#" class="btn btn-light" style="inline; border-radius:0px">-->
<!--                    <img src="{% static 'icons/board_icon.svg' %}" alt="add_icon">-->
<!--                    <div style="font-family:Noto Sans KR">게시판</div>-->
<!--                </a>-->
                {% if user.is_authenticated %}
                <a href="{% url 'app:personal_color' %}" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/pc_icon.png' %}" alt="add_icon">
                    <div style="font-family:Noto Sans KR">컬러</div>
                </a>
                <a href="{% url 'app:mycloset' %}" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/closet_icon.png' %}"alt="add_icon">
                    <div style="font-family:Noto Sans KR">옷장</div>
                </a>
                <a href="{% url 'app:my' %}" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/my_icon.svg' %}"alt="add_icon">
                    <div style="font-family:Noto Sans KR">마이</div>
                </a>
                <a href="{% url 'app:logout' %}" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/my_icon.svg' %}"alt="add_icon">
                    <div style="font-family:Noto Sans KR">로그아웃</div>
                </a>
                {% else %}
                <a href="{% url 'app:login' %}" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/login.svg' %}" alt="add_icon" style="width: 24px;height: 24px;">
                    <div style="font-family:Noto Sans KR">로그인</div>
                </a>
                {% endif %}
            </div>
        </nav>
    </div>
</body>
</html>