my_ootd/app/urls.py
from django.urls import path, reverse_lazy, reverse
from django.contrib.auth import views as auth_views
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.root, name='root'),
    path('my', views.my, name='my'),
    path('sign-up', views.sign_up, name='sign_up'),
    path('login', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    # path('logout', auth_views.LogoutView.as_view(template_name='app/main.html'), name='logout'),
    path('logout', views._logout, name='logout'),
    path('color', views.personal_color, name='personal_color'),
    path('mycloset', views.post_cloth, name='mycloset'),
    path('update_cloth', views.update_cloth, name='update_cloth'),
    path('create_user', views.create_user, name='create_user'),
    path('color_match_test', views.get_close_color, name='color_match_test'),
    path('select_color_test', views.select_color_test, name='select_color_test'),

    # ajax
    path('retry_recommend_cody', views.retry_recommend_cody, name='retry_recommend_cody'),
    path('save_my_style', views.save_my_style, name='save_my_style'),
    path('clothes_category', views.clothes_category, name='clothes_category'),
]

my_ootd/my_ootd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_ootd/app/templates/app/cloth_update.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<style>
    .clothes_image { /*해당 항목에 대한 스타일 지정*/
        border: 5px solid black;
        width: 200px;
        height: 200px;
        border-radius: 20px;
        margin: 20px auto; /* Center-align the image horizontally and add vertical margin */
        display: block; /* Ensures the image is treated as a block element */
    }

    .main { /*해당 항목에 대한 스타일 지정*/
        display: inline-block;
        width: auto;
        padding: 50px; /*요소 내부와 테두리 간격*/
    }

    .update-btn{
        font-size: auto;
        padding: 5px 20px;
        border: 2px solid black;
        background-color: skyblue;
        border-radius: 10px;
    }

     .moding  {
        display: flex;
        justify-content: center;
        border-bottom: 2px solid black;
        margin-top: 20px;

    }

    input, select, button {
        border: 2px solid black;
        padding: 5px;
        margin: 2px;
        border-radius: 10px;

</style>

<script>
    // 특수문자 입력 방지
    function characterCheck(obj){
    var regExp = /[\{\}\[\]\/?.,;:|\)*~`!^\-_+┼<>@\#$%&\'\"\\\(\=]/gi; 
    // 허용할 특수문자는 위에서 삭제
    // 띄어쓰기도 특수문자 처리
    if( regExp.test(obj.value) ){
        alert("특수문자는 입력하실수 없습니다.");
        obj.value = obj.value.substring( 0 , obj.value.length - 1 ); // 입력한 특수문자 한자리 지움
        }
    }
</script>

<div class="moding" >
<form method="post" action="{% url 'app:update_cloth' %}" enctype="multipart/form-data">
    {% csrf_token %}

    <input type="text" name="update_cloth_name" value="{{ update.cloth_name }}" onkeyup="characterCheck(this)" onkeydown="characterCheck(this)" required/>
    <select name="update_cloth_var" required>
        <option value="top">상의</option>
        <option value="pants">바지</option>
        <option value="outer">아우터</option>
        <option value="shoes">신발</option>
        <option value="accessory">악세사리</option>
    </select>

    <label for="update_cloth_col_1" class="color-label"><strong>색상1:</strong></label>
    <input type="color" name="update_cloth_col_1" value="{{ update.cloth_col_1 }}" onkeyup="characterCheck(this)" onkeydown="characterCheck(this)" required/>

    <label for="update_cloth_col_2" class="color-label"><strong>색상2:</strong></label>
    <input type="color" name="update_cloth_col_2" value="{{ update.cloth_col_2 }}" onkeyup="characterCheck(this)" onkeydown="characterCheck(this)" required/>

    <input type="file" name="update_cloth_img">
    


    <input type="hidden" name="previouspage" value="{{ request.path }}">
    <button type="submit" name="updateConfirm" class="update-btn" value="{{ update.id }}">수정</button>

</form>
</div>

<img src="{{ update.cloth_img.url }}" class="clothes_image"><br />
<hr>

{% endblock%}

my_ootd/app/templates/app/clothes.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<style>
    .clothes_image { /*해당 항목에 대한 스타일 지정*/
        border: 5px solid black; /*테두리 두께*/
        width: 200px; /*너비*/
        height: 200px; /*높이*/
        border-radius: 20px;
        margin-bottom: 5px;
    }

    .main { /*해당 항목에 대한 스타일 지정*/
        display: inline-block;
        width: auto;
        padding: 50px; /*요소 내부와 테두리 간격*/
    }

     .update-btn, .delete-btn{
        font-size: auto;
        padding: 3px 10px;

        border: 2px solid black;
        background-color: skyblue;
    }

    .create-btn{
        font-size: auto;
        padding: 5px 20px;
        border: 2px solid black;
        background-color: skyblue;
        border-radius: 10px;
    }

     .moding  {
        display: flex;
        justify-content: center;
        border-bottom: 2px solid black;
        margin-top: 20px;

    }

    input, select, button {
        border: 2px solid black;
        padding: 5px;
        margin: 2px;
        border-radius: 10px;
    }

    .color-box {
        display: inline-block;
        width: 40px; /* 색상 박스의 너비 설정 */
        height: 20px; /* 색상 박스의 높이 설정 */
        margin-right: 5px;
        border: 2px solid black;
        border-radius: 7px;
        vertical-align: middle;
    }

    .color1 {
        background-color: var(--cloth-col-1);
    }

    .color2 {
        background-color: var(--cloth-col-2);
    }

</style>

<script>
    // 특수문자 입력 방지
    function characterCheck(obj){
    var regExp = /[\{\}\[\]\/?.,;:|\)*~`!^\-_+┼<>@\#$%&\'\"\\\(\=]/gi;
    // 허용할 특수문자는 위에서 삭제
    // 띄어쓰기도 특수문자  처리
    if( regExp.test(obj.value) ){
        alert("특수문자는 입력/사용 하실수 없습니다.");
        obj.value = obj.value.substring( 0 , obj.value.length - 1 ); // 입력한 특수문자 한자리 지움
        }
    }
</script>

<div class="moding">
<form method="post" action="{% url 'app:mycloset' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="cloth_name" onkeyup="characterCheck(this)" onkeydown="characterCheck(this)" placeholder="이름을 작성해주세요.">
    <select name="cloth_var">
        <option value="top">상의</option>
        <option value="pants">바지</option>
        <option value="outer">아우터</option>
        <option value="shoes">신발</option>
        <option value="accessory">악세사리</option>
    </select>

    <label for="cloth_col_1" class="color-label"><strong>색상1:</strong></label>
    <input type="color" name="cloth_col_1" onkeyup="characterCheck(this)" onkeydown="characterCheck(this)">

    <label for="cloth_col_2" class="color-label"><strong>색상2:</strong></label>
    <input type="color" name="cloth_col_2" onkeyup="characterCheck(this)" onkeydown="characterCheck(this)">

    <input type="file" name="cloth_img">

    <button type="submit"  name="create_cloth" class=" create-btn">저장</button>
</form>
</div>
    {% for queryset in userdata %}
    <div class="main" >
        <img src="{{ queryset.cloth_img.url }}" class="clothes_image">
        <br>
        <hr>
        <strong>-이름: {{ queryset.cloth_name }} </strong>  <br>
        <strong>-종류: {{ queryset.cloth_var }}</strong> <br>
        <strong>-색상1: <span class="color-box color1" style="background-color: {{ queryset.cloth_col_1 }}"></span></strong> <br>
        <strong>-색상2: <span class="color-box color2" style="background-color: {{ queryset.cloth_col_2 }}"></span></strong> <br>

        <form action="{% url 'app:mycloset' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="update-btn" name="update_cloth" value="{{ queryset.id }}">수정</button>
            <button type="submit" class="delete-btn" name="delete_cloth" value="{{ queryset.id }}">삭제</button>
        </form>
    <hr>
    </div>
    {% endfor %}
{% endblock%}

my_ootd/app/templates/app/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

my_ootd/app/templates/app/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8" />
	<title>로그인</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0" />
    <meta name="format-detection" content="telephone=no" />
    <!-- 부트스트랩 css 사용 -->
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'custom.css' %}">
    <link rel="apple-touch-icon" href="경로/이미지파일명.png" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <style>
        body { background-color:#e9ecef; font-family: LINESeedKR-Bd}
    </style>
</head>
<body>
	<div id="app">
        <header id="header" style="height:250px" class="position-relative mb-5">
            <div class="container-fluid w-100">
                <div class="header position-absolute bottom-0 start-50 translate-middle-x" style="width:200px">
                    <a class="navbar-brand" href="{% url 'app:root' %}">
                        <img src="{% static 'icons/logo_icon.png' %}" alt="Logo" width="40" height="32" class="d-inline-block align-text-top">
                        <h1 style="display:inline; font-family:SEBANG_Gothic_Bold; vertical-align: bottom">#My_OOTD</h1>
                    </a>
                </div>
            </div>
        </header>

        <div id="container-fluid" class="position-relative">
            <div class="user_idpw">
                <form method="post" action="{% url 'app:login' %}">
                    {% csrf_token %}
                    {% include "app/form_errors.html" %}
                    <div class="input-group p-2 px-4">
                        <input type="text" name="{{ form.username.name }}" class="form-control" placeholder="아이디" aria-label="이메일" aria-describedby="basic-addon1" >
                    </div>
                    <div class="input-group p-2 px-4">
                        <input type="password" name="{{ form.password.name }}" class="form-control" placeholder="비밀번호" aria-label="비밀번호" aria-describedby="basic-addon1">
                    </div>
                    <div class="login_button p-2 px-4">
                        <input type="submit" class="btn btn-dark w-100" value="Login">
                    </div>
                </form>
            </div>

            <ul class="find_info row justify-content-center mt-4 w-100" style="list-style: none;">
<!--                <li class="col-4 text-center" style="float:left;">-->
<!--                    <a href="#">아이디 찾기</a>-->
<!--                </li>-->
<!--                <li class="col-4 text-center" style="float:left;">-->
<!--                    <a href="#">비밀번호 찾기</a>-->
<!--                </li>-->
                <li class="col-4 text-center" style="float:left;">
                    <a href="{% url 'app:sign_up' %}">회원가입</a>
                </li>
            </ul>
        </div>
    </div>
</body>
</html>

my_ootd/app/templates/app/main.html
{% extends 'base.html' %}

{% comment %} 
템플릿 상속 사용법:
1. {% extends 'base.html' %}를 제일 처음 라인에 작성
2. {% load static %}를 작성해서 스태틱 파일 로드
3. {% block content %}과 {% endblock%}태그를 작성하고 태그 사이에 해당 페이지에 대한 내용 작성 
{% endcomment %}

{% load static %}
{% block content %}
        <div id="container">
            <div class="weather_container container-fluid my-4">
                <h3 style="font-family: TheJamsil5Bold"><a class="navbar-brand" href="#">   오늘의 날씨</a></h3>
                <div class="card d-flex align-items-center justify-content-center">
<!--                    <img src="{% static 'image/weather.png' %}" alt="Weather" class="card-image m-1 img-thumbnail">-->
<!--                    <div style="max-width:100%" id="ww_99af52cb7f059" v='1.3' loc='id' a='{"t":"horizontal","lang":"ko","sl_lpl":1,"ids":["wl2309"],"font":"Arial","sl_ics":"one_a","sl_sot":"celsius","cl_bkg":"image","cl_font":"#FFFFFF","cl_cloud":"#FFFFFF","cl_persp":"#81D4FA","cl_sun":"#FFC107","cl_moon":"#FFC107","cl_thund":"#FF5722","el_whr":3}'>Weather Data Source: <a href="https://wetterlabs.de/wetter_daegu/woche/" id="ww_99af52cb7f059_u" target="_blank">wetterlabs.de/wetter_daegu/woche/</a></div><script async src="https://app1.weatherwidget.org/js/?id=ww_99af52cb7f059"></script>-->
                    <img src="{% get_static_prefix %}icons/weather/{{ request.session.weather_icon_filename }}" style="max-width: 100px; height: auto;">
                    <strong style="font-size: 30px;">최고:<span style="color: red;">{{ request.session.weather.TMX }}</span>°C / 최저:<span style="color: blue;">{{ request.session.weather.TMN }}</span>°C</strong>
                    <strong style="font-size: 15px;">강수확률:{{ request.session.weather.POP }}% / 최대풍속:{{ request.session.weather.WSD }}m/s</strong>
                </div>
            </div>
            <hr class="m-3">
            <div class="dail_code container-fluid m-3 mx-2">
                <h3 style="font-family: TheJamsil5Bold"><a class="navbar-brand" href="#">데일리 코디</a></h3>
                <div class="card cody h-100">
                    <div class="row row-cols-2">
    <!--                <img src="{% static 'image/daily_code.jpg' %}" class="card-img-top" alt="daily_code" id="daily_code_img">-->
                        {% if cody.top %}
                        <div class="col">
                            <img src="/media/{{cody.top}}" id="top" class="card-img-top" alt="daily_code">
                        </div>
                        {% endif %}
                        {% if cody.pants %}
                        <div class="col">
                            <img src="/media/{{cody.pants}}" id="pants" class="card-img-top" alt="daily_code">
                        </div>
                        {% endif %}
                        {% if cody.outer %}
                        <div class="col">
                            <img src="/media/{{cody.outer}}" id="outer" class="card-img-top" alt="daily_code">
                        </div>
                        {% endif %}
                        {% if cody.shoes %}
                        <div class="col">
                            <img src="/media/{{cody.shoes}}" id="shoes" class="card-img-top" alt="daily_code">
                        </div>
                        {% endif %}
                        {% if cody.accessory %}
                        <div class="col">
                            <img src="/media/{{cody.accessory}}" id="acc" class="card-img-top" alt="daily_code">
                        </div>
                        {% endif %}
                    </div>

                    <div class="card-body row justify-content-around" style="font-family:Noto Sans KR;">
                        <button id="save_mystyle" class="btn btn-secondary col mx-2" style="inline">스타일 등록하기</button>
                        <script>
                            $('#save_mystyle').on('click', ()=>{
                                $.ajax({
                                    type: 'POST',
                                    url: '{% url 'app:save_my_style' %}',
                                    data: {},
                                    success:(msg)=>{
                                        console.log(msg);
                                    },
                                    error: (xhr, errmsg, err)=>{
                                        console.log(xhr.status + ": " + xhr.responseText);
                                    }
                                })
                            })
                        </script>
                        <button id="re_rcm" class="btn btn-secondary col mx-2" style="inline">다시 추천하기</button>
                        <script>
                            $('#re_rcm').on('click', ()=>{
                                $.ajax({
                                    type: 'POST',
                                    url: '{% url 'app:retry_recommend_cody' %}',
                                    data: {},
                                    success:(data)=>{
                                        var res = JSON.parse(data);
                                        m = '/media/'
                                        $('#top').attr('src', res.top ? m + res.top : $('#top').attr('src'));
                                        $('#pants').attr('src', res.pants ? m + res.pants : $('#pants').attr('src'));
                                        $('#outer').attr('src', res.outer ? m + res.outer : $('#outer').attr('src'));
                                        $('#shoes').attr('src', res.shoes ? m + res.shoes : $('#shoes').attr('src'));
                                        $('#acc').attr('src', res.accessory ? m + res.accessory : $('#acc').attr('src'));
                                    },
                                    error: (xhr, errmsg, err)=>{
                                        console.log(xhr.status + ": " + xhr.responseText);
                                    }
                                })
                            })
                        </script>
                    </div>
                </div>
            </div>
            <div class="modal_overlay" id="modal_daily_code_img" style="z-index: 100;">
                <div class="modal_window">
                    <div class="modal_title">
                        <div class="modal_title_side"></div>
                        <div> 데일리 수정 </div>
                        <div class="modal_title_side">
                            <span id="close_modal">
                                close
                            </span>
                        </div>                        
                    </div>
                    <div class="modal_daily_code_img_update">
                        <img src="{% static 'image/style1.jpg' %}" class="card-img-top" alt="daily_code_to_update">
                        <button type="button" class="btn btn-primary"  id="daily_code_img_to_update">수정</button>

                    </div>
                </div>
            </div>
            <script type="text/javascript" src="{% static 'modal.js' %}"></script>
            <hr class="m-3">
            <div class="my_closet container-fluid m-3 mx-2">
                <h3 style="font-family: TheJamsil5Bold"><a class="navbar-brand" href="#">내 옷장</a></h3>
                <div class="clothes_category my-3" style="font-family:LINESeedKR-Bd; overflow-x:auto; white-space:nowrap;">
                    <button type="button" class="btn btn-light btn_cg" category="{{category.0}}">상의</button>
                    <button type="button" class="btn btn-light btn_cg" category="{{category.1}}">하의</button>
                    <button type="button" class="btn btn-light btn_cg" category="{{category.2}}">아우터</button>
                    <button type="button" class="btn btn-light btn_cg" category="{{category.3}}">신발</button>
                    <button type="button" class="btn btn-light btn_cg" category="{{category.4}}">악세서리</button>
                </div>
                <script>
                var a;
                $(document).ready(function() {
                    $('.btn_cg').click(function() {
                        console.log($(this).attr('category'))
                        $.ajax({
                            type: 'POST',
                            url: '{% url 'app:clothes_category' %}',
                            data: { 'category': $(this).attr('category') },
                            success:(data)=>{
                                $('#closet').empty();
                                JSON.parse(data.replace(/'/g, '"')).forEach(e => {
                                    $('#closet').append('<div class="col"><div class="card h-100"><img src="\/media\/'+e+'" class="card-img-top"></div>');
                                });
                            },
                            error: (xhr, errmsg, err)=>{
                                console.log(xhr.status + ": " + xhr.responseText);
                            }
                        })
                    })
                })
                </script>
                <div class="top_clothes row row-cols-2 row-cols-md-2 g-4" id="closet">
                    {% for queryset in userdata %}
                    <div class="col">
                        <div class="card h-100">
                            <img src="{{ queryset.cloth_img.url }}" class="card-img-top">
                        </div>
                    </div>
                    {% endfor %}
                    <!--
                    <div class="col">
                        <div class="card h-100">
                        <img src="{% static 'image/tshirt2.jpg' %}" class="card-img-top" alt="top">
                        </div>
                    </div>
                    -->
                </div>
                <!--<script type="text/javascript" src="{% static 'mycloset.js' %}"></script>-->
            </div>
            <hr class="m-3 my-2">
            <div class="my_style container-fluid m-3 mx-2 mb-5">
                <h3 style="font-family: TheJamsil5Bold"><a class="navbar-brand" href="#">내 스타일</a></h3>
                <div class="my_style_list row row-cols-2 row-cols-md-2 g-4">
                    {% for cody_logs in saved_cody %}
                    <div class="col">
                        <div class="card h-100">
                            <div class="row row-cols-2">
                            {% for c in cody_logs %}
                                <div class="col">
                                    <img src="media/{{c}}" class="card-img-top">
                                </div>
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock%}

my_ootd/app/templates/app/main_page.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />
    <title>Mobile Coding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0" />
    <meta name="format-detection" content="telephone=no" />
    <!-- 부트스트랩 css 사용 -->
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'custom.css' %}">
    <link rel="apple-touch-icon" href="경로/이미지파일명.png" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">

    <style>
    </style>

</head>

<body>
    <div id="app">
        <header id="header">
            <nav class="navbar bg-white border-bottom">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">
                        <img src="{% static 'icons/logo_icon.png' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
                        <h3 style="display:inline; font-family:SEBANG_Gothic_Bold">#My_OOTD</h3>
                    </a>
                    <div class="top_icons">
                        <div class="search_button px-1 ">
                            <a href="#">
                            <img src="{% static 'icons/search_icon.svg' %}" alt="Search" width="30" height="24" class="d-inline-block align-text-top" >   
                            </a>
                        </div>
                        <div class="notification_button px-1 position-relative">
                            <a href="#">
                            <img src="{% static 'icons/bell_icon.svg' %}" alt="Notification" width="30" height="24" class="d-inline-block align-text-top">
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>

        <div id="container">
            <div class="weather_container container-fluid my-4">
                <div class="card">
                    <img src="{% static 'image/weather.png' %}" alt="Weather" class="card-image m-1 img-thumbnail">
                </div>
            </div>
            <hr class="m-3">
            <div class="dail_code container-fluid m-3 mx-2">
                <h3 style="font-family: TheJamsil5Bold">데일리 코디</h3>
                <div class="card">
                    <img src="{% static 'image/daily_code.jpg' %}" class="card-img-top" alt="daily_code">
                    <div class="card-body row justify-content-around" style="font-family:Noto Sans KR;">
                        <a href="#" class="btn btn-secondary col mx-2" style="inline">스타일 등록하기</a>
                        <a href="#" class="btn btn-secondary col mx-2" style="inline">다시 추천하기</a>
                    </div>
                </div>
            </div>
            <hr class="m-3">
            <div class="my_closet container-fluid m-3 mx-2">
                <h3 style="font-family: TheJamsil5Bold">내 옷장</h3>
                <div class="clothes_category my-3" style="font-family:LINESeedKR-Bd; overflow-x:auto; white-space:nowrap;">
                    <button type="button" class="btn btn-light" style=>모자</button>
                    <button type="button" class="btn btn-light">아우터</button>
                    <button type="button" class="btn btn-light">상의</button>
                    <button type="button" class="btn btn-light">하의</button>
                    <button type="button" class="btn btn-light">원피스</button>
                    <button type="button" class="btn btn-light">신발</button>
                    <button type="button" class="btn btn-light">악세사리</button>
                </div>
                <div class="top_clothes row row-cols-2 row-cols-md-2 g-4">
                    <div class="col">
                        <div class="card h-100">
                        <img src="{% static 'image/tshirt1.jpg' %}" class="card-img-top" alt="top">
                        </div>
                    </div>

                    <div class="col">
                        <div class="card h-100">
                        <img src="{% static 'image/tshirt2.jpg' %}" class="card-img-top" alt="top">
                        </div>
                    </div>
                    <div class="col">
                        <div class="card h-100">
                        <img src="{% static 'icons/add_icon.png' %}" class="card-img-top img-thumbnail" alt="add_icon">
                        </div>
                    </div>
                </div>
            </div>
            <hr class="m-3 my-2">
            <div class="my_style container-fluid m-3 mx-2 mb-5">
                <h3 style="font-family: TheJamsil5Bold">내 스타일</h3>
                <div class="my_style_list row row-cols-2 row-cols-md-2 g-4">
                    <div class="col">
                        <div class="card h-100">
                        <img src="{% static 'image/style1.jpg' %}" class="card-img-top" alt="top">
                        </div>
                    </div>
                    <div class="col">
                        <div class="card h-100">
                        <img src="{% static 'image/style2.jpg' %}" class="card-img-top" alt="top">
                        </div>
                    </div>
                    <div class="col">
                        <div class="card h-100">
                        <img src="{% static 'icons/add_icon.png' %}" class="card-img-top img-thumbnail" alt="add_icon">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer id="footer">
            <div class="py-5 bg-dark container-fluid px-4"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
            <div class="py-4 bg-dark container-fluid"></div>
        </footer>

        <nav id="fixed_bar">
            <div class="bottom_nav_bar btn-group" style="width:100%">
                <a href="{% url 'app:root' %}" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/home_icon.svg' %}" alt="add_icon">
                    <div style="font-family:Noto Sans KR">홈</div>
                </a>
<!--                <a href="#" class="btn btn-light" style="inline; border-radius:0px">-->
<!--                    <img src="{% static 'icons/board_icon.svg' %}" alt="add_icon">-->
<!--                    <div style="font-family:Noto Sans KR">게시판</div>-->
<!--                </a>-->
                {% if user.is_authenticated %}
                <a href="#" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/pc_icon.png' %}" alt="add_icon">
                    <div style="font-family:Noto Sans KR">컬러</div>
                </a>
                <a href="{% url 'app:mycloset' %}" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/closet_icon.png' %}"alt="add_icon">
                    <div style="font-family:Noto Sans KR">옷장</div>
                </a>
                <a href="#" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/my_icon.svg' %}"alt="add_icon">
                    <div style="font-family:Noto Sans KR">마이</div>
                </a>
                <a href="{% url 'app:logout' %}" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/my_icon.svg' %}"alt="add_icon">
                    <div style="font-family:Noto Sans KR">로그아웃</div>
                </a>
                {% else %}
                <a href="{% url 'app:login' %}" class="btn btn-light" style="inline; border-radius:0px">
                    <img src="{% static 'icons/login.svg' %}" alt="add_icon" style="width: 24px;height: 24px;">
                    <div style="font-family:Noto Sans KR">로그인</div>
                </a>
                {% endif %}
            </div>
        </nav>
    </div>
</body>
</html>

my_ootd/app/templates/app/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{# TODO #5 비밀번호 등 양식에 맞지않을때 경고 표시 #}
<form action="{% url 'app:sign_up' %}" method="post">
    {% csrf_token %}
    ID:{{form.username}}<br>
    PW:{{form.password1}}<br>
    PW2:{{form.password2}}<br>
    e-mail:{{form.email}}<br>
    nick:{{form.nickname}}<br>
    Gender:{{form.is_male}}<br>
    phone:{{form.phone}}<br>
    skin color:{{form.skin_color}}<br>
    <input type="submit" value="회원가입">
</form>
<a href="{% url 'app:root' %}">홈으로</a>
</body>
</html>

my_ootd/app/templates/app/weather.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>weather</title>
</head>
<body>
{{contents}}
</body>
</html>